apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-cluster-config
data:
  config.xml: |
    <clickhouse replace="true">
      <logger>
        <level>information</level>
        <log>/var/log/clickhouse-server/clickhouse-server.log</log>
        <errorlog>/var/log/clickhouse-server/clickhouse-server.err.log</errorlog>
        <size>1000M</size>
        <count>3</count>
      </logger>
        
      <listen_host>0.0.0.0</listen_host>
      <http_port>8123</http_port>
      <tcp_port>9000</tcp_port>
      <!-- Replica'lar arası iletişim için gerekli -->
      <interserver_http_port>9009</interserver_http_port>
        
      <user_directories>
        <users_xml>
          <path>users.xml</path>
        </users_xml>
        <local_directory>
          <path>/var/lib/clickhouse/access/</path>
        </local_directory>
      </user_directories>
        
      <distributed_ddl>
        <path>/clickhouse/task_queue/ddl</path>
      </distributed_ddl>
        
      <remote_servers>
        <cluster_2R_2S>
          <shard>
            <internal_replication>true</internal_replication>
            <replica>
              <host>clickhouse-cluster-0.clickhouse-headless.default.svc.cluster.local</host>
              <port>9000</port>
              <user>default</user>
              <password></password>
            </replica>
            <replica>
              <host>clickhouse-cluster-1.clickhouse-headless.default.svc.cluster.local</host>
              <port>9000</port>
              <user>default</user>
              <password></password>
            </replica>
          </shard>
          <shard>
            <internal_replication>true</internal_replication>
            <replica>
              <host>clickhouse-cluster-2.clickhouse-headless.default.svc.cluster.local</host>
              <port>9000</port>
              <user>default</user>
              <password></password>
            </replica>
            <replica>
              <host>clickhouse-cluster-3.clickhouse-headless.default.svc.cluster.local</host>
              <port>9000</port>
              <user>default</user>
              <password></password>
            </replica>
          </shard>
        </cluster_2R_2S>
      </remote_servers>
        
      <zookeeper>
        <node>
          <host>zookeeper-0.zookeeper-headless.zookeeper.svc.cluster.local</host>
          <port>2181</port>
        </node>
        <node>
          <host>zookeeper-1.zookeeper-headless.zookeeper.svc.cluster.local</host>
          <port>2181</port>
        </node>
        <node>
          <host>zookeeper-2.zookeeper-headless.zookeeper.svc.cluster.local</host>
          <port>2181</port>
        </node>
      </zookeeper>
        
      <macros>
        <shard from_env="SHARD_ID"></shard>
        <replica from_env="REPLICA_ID"></replica>
      </macros>
    </clickhouse>
  
  users.xml: |
    <?xml version="1.0"?>
    <clickhouse replace="true">
      <profiles>
        <default>
          <max_memory_usage>10000000000</max_memory_usage>
          <use_uncompressed_cache>0</use_uncompressed_cache>
          <load_balancing>in_order</load_balancing>
          <log_queries>1</log_queries>
        </default>
      </profiles>
      <users>
        <default>
          <access_management>1</access_management>
          <profile>default</profile>
          <networks>
            <ip>::/0</ip>
          </networks>
          <quota>default</quota>
          <named_collection_control>1</named_collection_control>
          <show_named_collections>1</show_named_collections>
          <show_named_collections_secrets>1</show_named_collections_secrets>
        </default>
      </users>
      <quotas>
        <default>
          <interval>
            <duration>3600</duration>
            <queries>0</queries>
            <errors>0</errors>
            <result_rows>0</result_rows>
            <read_rows>0</read_rows>
            <execution_time>0</execution_time>
          </interval>
        </default>
      </quotas>
    </clickhouse>