apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
spec:
  type: LoadBalancer
  selector:
    app: clickhouse-cluster
  ports:
  - port: 8123
    targetPort: 8123
    name: http
  - port: 9000
    targetPort: 9000
    name: native